export const FETCH_CART_REQUEST = 'FETCH_CART_REQUEST'
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS'
export const FETCH_CART_FAILURE = 'FETCH_CART_FAILURE'

export const CREATE_CART_REQUEST = 'CREATE_CART_REQUEST'
export const CREATE_CART_SUCCESS = 'CREATE_CART_SUCCESS'
export const CREATE_CART_FAILURE = 'CREATE_CART_FAILURE'